### PR TITLE
Don't Merge: Add more guidance and template headings for AutoExch

### PR DESCRIPTION
**Pull request by annegentle**

### CODE REVIEW

**Review by eckelcu — COMMENTED** [review]
These additional the use case template look good. Would be good to integrate into the README, https://github.com/CiscoDevNet/code-exchange-repo-template/tree/ag-usecase-templ/manual-sample-repo#use-case-description.

**Comment by annegentle** [comment]
Oh good catch @eckelcu - thanks, will do.

**Review by oborys — CHANGES_REQUESTED** [review]
I also suggest adding chapter 

## Links to DevNet Learning Labs (if applicable)
- [Links to Related DevNet Learning Lab/Modules](https://developer.cisco.com/learning/labs)

**Comment by annegentle** [comment]
> I also suggest adding chapter
> 
> ## Links to DevNet Learning Labs (if applicable)
> * [Links to Related DevNet Learning Lab/Modules](https://developer.cisco.com/learning/labs)
Thanks for the review! 
For sure I kept those sections, they just get condensed in the review pane. 
Screen Shot 2021-07-20 at 11 57 33 AM

**Comment by Geevarghese** [comment]
White Paper/Cisco Blogs  - Because many repos the motivation will be the blogs

**Review by eckelcu — COMMENTED** [review]
Looks good, though I would probably replace USECASE.md with [USECASE](./USECASE.md).
Note, manuall-sample-repo/README.md needs to updated similarly.
Perhaps there is a better way to deal with this than having duplicate files in the two directories, but that is how it was dealt with when the cookie cutter option was added.

**Comment by annegentle** [comment]
With the merge between AE and CE, this PR is no longer relevant, closing,

**Pull request closed without merging**
